spring.application.name=book-my-show
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:postgresql://localhost:5432/bookmy_show
spring.datasource.username=sachinksiby
spring.datasource.password=Sachin@2026
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true